development:
  :address: 192.168.33.21
  :port: 25
  :authentication: none
  #:user_name: xxx
  #:password: yyy
  #:enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: xxx
  :password: yyy
  :enable_starttls_auto: true